drop user c##rest;
--계정생성
CREATE USER c##rest IDENTIFIED BY rest123
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    PROFILE DEFAULT;
--권한부여
GRANT CONNECT, RESOURCE TO c##rest;
GRANT CREATE VIEW, CREATE SYNONYM TO c##rest;
GRANT UNLIMITED TABLESPACE TO c##rest;
--락 풀기
ALTER USER c##rest ACCOUNT UNLOCK;